"""
Modal Fine-Tuning Script for Alpha Signal Analysis Platform

Runs QLoRA fine-tuning of Qwen3-8B using Unsloth on Modal's serverless GPUs.
Uses the training dataset generated by the teacher model (Qwen3.7-Max).

Usage:
    modal run scripts/modal_finetune.py
    modal run scripts/modal_finetune.py --dataset-path data/training/quantum_alpha_train.jsonl
"""

import modal

# Modal app definition
app = modal.App("quantum-alpha-finetune")

# Container image with all dependencies
finetune_image = (
    modal.Image.from_registry("nvidia/cuda:12.4.0-devel-ubuntu22.04", add_python="3.11")
    .entrypoint([])
    .apt_install("git")
    .pip_install(  # Install PyTorch first (required by flash-attn build)
        "torch",
        "torchvision",
        "torchaudio",
    )
    .pip_install(  # Install core ML deps
        "datasets",
        "huggingface_hub",
        "trl",
        "transformers",
        "accelerate",
        "peft",
        "bitsandbytes",
        "wandb",
        "xformers",
    )
    .run_commands(  # Install Unsloth separately (needs torch available)
        "pip install --no-deps unsloth unsloth-zoo",
        "pip install --no-deps cut-cross-entropy sentencepiece protobuf",
    )
    .env({"HF_XET_HIGH_PERFORMANCE": "1"})
)

# Volume for caching model weights and saving outputs
hf_cache_vol = modal.Volume.from_name("hf-cache-quantum-alpha", create_if_missing=True)
output_vol = modal.Volume.from_name("quantum-alpha-outputs", create_if_missing=True)

# Training configuration
TRAINING_CONFIG = {
    "base_model": "Qwen/Qwen3-8B",
    "max_seq_length": 4096,
    "lora_rank": 64,
    "lora_alpha": 16,
    "lora_dropout": 0,
    "learning_rate": 5e-5,
    "num_epochs": 4,
    "per_device_train_batch_size": 2,
    "gradient_accumulation_steps": 4,
    "warmup_steps": 10,
    "weight_decay": 0.01,
    "lr_scheduler_type": "linear",
    "seed": 42,
    "output_dir": "/outputs/quantum-alpha-qwen3-8b",
    "hub_model_id": "basilwong/quantum-alpha-qwen3-8b",
}


@app.function(
    image=finetune_image,
    gpu="A100",
    timeout=3600,  # 1 hour max
    volumes={
        "/root/.cache/huggingface": hf_cache_vol,
        "/outputs": output_vol,
    },
    secrets=[modal.Secret.from_name("huggingface-secret")],
)
def train(dataset_path: str = "/outputs/quantum_alpha_train.jsonl"):
    """Run the QLoRA fine-tuning job."""
    import os
    from unsloth import FastLanguageModel
    from datasets import load_dataset
    from trl import SFTTrainer

    print("=" * 60)
    print("QUANTUM ALPHA INTELLIGENCE: Fine-Tuning Pipeline")
    print("=" * 60)
    print(f"Base model: {TRAINING_CONFIG['base_model']}")
    print(f"LoRA rank: {TRAINING_CONFIG['lora_rank']}")
    print(f"Learning rate: {TRAINING_CONFIG['learning_rate']}")
    print(f"Epochs: {TRAINING_CONFIG['num_epochs']}")
    print(f"Dataset: {dataset_path}")
    print("=" * 60)

    # Load the base model with 4-bit quantization
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=TRAINING_CONFIG["base_model"],
        max_seq_length=TRAINING_CONFIG["max_seq_length"],
        dtype=None,  # Auto-detect
        load_in_4bit=True,
    )

    print("Model loaded successfully.")

    # Apply LoRA adapters
    model = FastLanguageModel.get_peft_model(
        model,
        r=TRAINING_CONFIG["lora_rank"],
        lora_alpha=TRAINING_CONFIG["lora_alpha"],
        lora_dropout=TRAINING_CONFIG["lora_dropout"],
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=TRAINING_CONFIG["seed"],
    )

    print("LoRA adapters applied.")

    # Load the training dataset
    dataset = load_dataset("json", data_files=dataset_path, split="train")
    print(f"Dataset loaded: {len(dataset)} examples")

    # Format the dataset into chat template
    def format_example(example):
        messages = example["messages"]
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False,
        )
        return {"text": text}

    dataset = dataset.map(format_example)

    from trl import SFTConfig

    # Training configuration
    sft_config = SFTConfig(
        output_dir=TRAINING_CONFIG["output_dir"],
        num_train_epochs=TRAINING_CONFIG["num_epochs"],
        per_device_train_batch_size=TRAINING_CONFIG["per_device_train_batch_size"],
        gradient_accumulation_steps=TRAINING_CONFIG["gradient_accumulation_steps"],
        learning_rate=TRAINING_CONFIG["learning_rate"],
        weight_decay=TRAINING_CONFIG["weight_decay"],
        warmup_steps=TRAINING_CONFIG["warmup_steps"],
        lr_scheduler_type=TRAINING_CONFIG["lr_scheduler_type"],
        logging_steps=10,
        save_strategy="epoch",
        save_total_limit=4,
        fp16=False,
        bf16=True,
        seed=TRAINING_CONFIG["seed"],
        report_to="none",
        dataset_text_field="text",
        max_seq_length=TRAINING_CONFIG["max_seq_length"],
        packing=True,
    )

    # Initialize the SFT trainer
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        args=sft_config,
    )

    print("Starting training...")
    trainer.train()
    print("Training complete!")

    # Save the model
    print(f"Saving model to {TRAINING_CONFIG['output_dir']}...")
    model.save_pretrained(TRAINING_CONFIG["output_dir"])
    tokenizer.save_pretrained(TRAINING_CONFIG["output_dir"])

    # Push to Hugging Face Hub
    hf_token = os.environ.get("HF_TOKEN")
    if hf_token:
        print(f"Pushing to HF Hub: {TRAINING_CONFIG['hub_model_id']}...")
        model.push_to_hub(
            TRAINING_CONFIG["hub_model_id"],
            token=hf_token,
            private=True,
        )
        tokenizer.push_to_hub(
            TRAINING_CONFIG["hub_model_id"],
            token=hf_token,
            private=True,
        )
        print("Model pushed to HF Hub successfully!")
    else:
        print("WARNING: HF_TOKEN not set. Model saved locally only.")

    # Save training metrics
    metrics = trainer.state.log_history
    print(f"\nFinal training loss: {metrics[-1].get('train_loss', 'N/A')}")

    return {
        "status": "complete",
        "final_loss": metrics[-1].get("train_loss"),
        "total_steps": trainer.state.global_step,
        "output_dir": TRAINING_CONFIG["output_dir"],
        "hub_model_id": TRAINING_CONFIG["hub_model_id"],
    }


@app.function(
    image=finetune_image,
    gpu="A100",
    timeout=600,
    volumes={
        "/root/.cache/huggingface": hf_cache_vol,
        "/outputs": output_vol,
    },
)
def test_setup():
    """Quick test to verify the environment works before running full training."""
    from unsloth import FastLanguageModel
    import torch

    print("Testing environment setup...")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # Test model loading
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=TRAINING_CONFIG["base_model"],
        max_seq_length=512,
        dtype=None,
        load_in_4bit=True,
    )
    print("Model loaded successfully!")
    print(f"Model parameters: {sum(p.numel() for p in model.parameters()) / 1e9:.2f}B")

    # Quick inference test
    FastLanguageModel.for_inference(model)
    messages = [
        {"role": "system", "content": "You are a quantum computing financial analyst."},
        {"role": "user", "content": "IonQ announced 35 algorithmic qubits. Is this bullish or bearish?"},
    ]
    inputs = tokenizer.apply_chat_template(messages, return_tensors="pt", add_generation_prompt=True).to("cuda")
    outputs = model.generate(inputs, max_new_tokens=200)
    response = tokenizer.decode(outputs[0][inputs.shape[-1]:], skip_special_tokens=True)
    print(f"\nTest inference output:\n{response[:500]}")

    return {"status": "environment_ready", "gpu": torch.cuda.get_device_name(0)}


@app.local_entrypoint()
def main(test: bool = False, dataset_path: str = "/outputs/quantum_alpha_train.jsonl"):
    """Entry point for running from the command line."""
    if test:
        result = test_setup.remote()
        print(f"Test result: {result}")
    else:
        result = train.remote(dataset_path=dataset_path)
        print(f"Training result: {result}")
